export const LOAD_SCHOOLS_START = "LOAD_SCHOOLS_START"
export const LOAD_SCHOOLS_RESULTS = 'LOAD_SCHOOLS_RESULTS';
export const LOAD_SCHOOLS_ERROR = 'LOAD_SCHOOLS_ERROR';


export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const INVALIDATE_TOKEN = 'INVALIDATE_TOKEN';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const LOAD_OPPORTUNITIES_SUCCESS = 'LOAD_OPPORTUNITIES_SUCCESS';
export const LOAD_OPPORTUNITIES_FAILURE = 'LOAD_OPPORTUNITIES_FAILURE';
export const CREATE_OPPORTUNITY_SUCCESS = 'CREATE_OPPORTUNITY_SUCCESS';
export const CREATE_OPPORTUNITY_FAILURE = 'CREATE_OPPORTUNITY_FAILURE';
export const UPDATE_OPPORTUNITY_SUCCESS = 'UPDATE_OPPORTUNITY_SUCCESS';
export const UPDATE_OPPORTUNITY_FAILURE = 'UPDATE_OPPORTUNITY_FAILURE';

export const LOAD_FIRMS_SUCCESS = 'LOAD_FIRMS_SUCCESS';
export const LOAD_FIRMS_FAILURE = 'LOAD_FIRMS_FAILURE';

export const LOAD_SCHOOLS_SUCCESS = 'LOAD_SCHOOLS_SUCCESS';
export const LOAD_SCHOOLS_FAILURE = 'LOAD_SCHOOLS_FAILURE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const DELETE_USER_INFO = 'DELETE_USER_INFO';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const DELETE_USER_ERRORS = 'DELETE_USER_ERRORS';
